import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '@/src/context/AuthContext';
import Navbar from '@/src/components/layout/Navbar';
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Freelance Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans flex flex-col min-h-screen antialiased`}>
        <AuthProvider>
          <Toaster position="top-right" richColors />
          
          {/* 1. NAVBAR */}
          <header className="p-4 bg-white border-b sticky top-0 z-50">
            <Navbar />
          </header>

          {/* 2. MAIN CONTENT */}
          <main className="flex-grow">
            {children}
          </main>

          {/* 3. FOOTER */}
          <footer className="p-4 bg-gray-100 text-center text-sm text-slate-600">
            © 2026 Moja Freelance Platforma
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}